const enUS: import('../types/i18n').SystemApiLang = {
  title: 'API Management',
  addApi: 'Add API',
  editApi: 'Edit API',
  deleteApi: 'Delete API',
  refresh: 'Refresh Cache',
  refreshSuccess: 'Cache refreshed successfully',
  batchDelete: 'Delete',
  assignRole: 'Assign Role',
  assignRoleNotice: 'Note: Saving will overwrite all role associations for this API and refresh Casbin cache.',
  assignRoleSuccess: 'Assigned successfully',
  roleTreeEmpty: 'No roles available',
  colSetting: 'Column Settings',
  selectAll: 'Select All',
  search: 'Search',
  searchTitle: 'Search API',
  reset: 'Reset',
  operation: 'Operation',
  index: 'ID',
  path: 'API Path',
  drawerPath: 'Path',
  apiGroup: 'API Group',
  drawerApiGroup: 'API Group',
  description: 'API Description',
  drawerDescription: 'API Description',
  descriptionSearch: 'Description',
  method: 'Request',
  drawerMethod: 'Request',
  drawerNotice: 'New APIs must be configured in role management before they can be used.',
  confirmDelete: 'Are you sure to delete this API?',
  confirmBatchDelete: 'Are you sure to batch delete the selected APIs?',
  pathPlaceholder: 'Please enter the path',
  pathSearchPlaceholder: 'Path',
  drawerPathPlaceholder: 'Please enter the api path',
  apiGroupPlaceholder: 'Please enter the API group',
  apiGroupSearchPlaceholder: 'Please select',
  drawerApiGroupPlaceholder: 'Select or create',
  descriptionPlaceholder: 'Please enter the description',
  descriptionSearchPlaceholder: 'Description',
  drawerDescriptionPlaceholder: 'Please enter the api description',
  methodPlaceholder: 'Please select the method',
  drawerMethodPlaceholder: 'Please select',
  addSuccess: 'Created successfully',
  editSuccess: 'Updated successfully',
  deleteSuccess: 'Deleted successfully'
};

export default enUS;
