const zhCN: import('../types/i18n').SystemApiLang = {
  title: '接口管理',
  addApi: '新增接口',
  editApi: '编辑接口',
  deleteApi: '删除接口',
  refresh: '刷新缓存',
  refreshSuccess: '缓存刷新成功',
  batchDelete: '删除',
  assignRole: '分配角色',
  assignRoleNotice: '注：保存时将全量覆盖该API的角色关联关系，并自动刷新Casbin缓存',
  assignRoleSuccess: '分配成功',
  roleTreeEmpty: '暂无角色',
  colSetting: '列设置',
  selectAll: '全选',
  search: '搜索',
  searchTitle: '搜索接口',
  reset: '重置',
  operation: '操作',
  index: 'ID',
  path: 'API路径',
  drawerPath: '路径',
  apiGroup: 'API分组',
  drawerApiGroup: 'api分组',
  description: 'API简介',
  drawerDescription: 'api简介',
  descriptionSearch: '描述',
  method: '请求',
  drawerMethod: '请求',
  drawerNotice: '新增API，需要在角色管理内配置权限才可使用',
  confirmDelete: '确定要删除该接口吗？',
  confirmBatchDelete: '确定要批量删除选中的接口吗？',
  pathPlaceholder: '请输入接口路径',
  pathSearchPlaceholder: '路径',
  drawerPathPlaceholder: '请输入api路径',
  apiGroupPlaceholder: '请输入接口分组',
  apiGroupSearchPlaceholder: '请选择',
  drawerApiGroupPlaceholder: '请选择或新增',
  descriptionPlaceholder: '请输入接口描述',
  descriptionSearchPlaceholder: '描述',
  drawerDescriptionPlaceholder: '请输入api介绍',
  methodPlaceholder: '请选择请求方式',
  drawerMethodPlaceholder: '请选择',
  addSuccess: '新增成功',
  editSuccess: '编辑成功',
  deleteSuccess: '删除成功'
};

export default zhCN;
