const timedTaskEnUS = {
  title: 'Timed Task',
  search: {
    name: 'Name',
    executorType: 'Executor',
    enabled: 'Enabled',
    method: 'Method',
    http: 'HTTP',
    search: 'Search',
    reset: 'Reset'
  },
  add: 'New Task',
  columns: {
    id: 'ID',
    name: 'Name',
    description: 'Description',
    spec: 'cron',
    executorType: 'Executor',
    methodExecutor: 'Method',
    httpExecutor: 'HTTP',
    enabled: 'Enabled',
    nextRunAt: 'Next Run',
    operations: 'Actions',
    trigger: 'Trigger',
    logs: 'Logs',
    edit: 'Edit',
    delete: 'Delete',
    cannotDeleteEnabled: 'Enabled tasks cannot be deleted'
  },
  form: {
    title: 'New Timed Task',
    editTitle: 'Edit Timed Task',
    name: 'Name',
    description: 'Description',
    spec: 'cron expression',
    cronTemplate: 'Common templates',
    withSeconds: 'With seconds',
    withSecondsHint: 'Enable for a 6-field expression (sec min hour day month week)',
    executor: 'Executor',
    methodExecutor: 'Call registered method',
    httpExecutor: 'HTTP call',
    method: 'Method',
    params: 'Params (JSON)',
    url: 'URL',
    httpMethod: 'Method',
    header: 'Header (JSON)',
    body: 'Body',
    allowPrivate: 'Allow private',
    allowPrivateHint: 'Private/loopback addresses are blocked by default (SSRF protection); enable only when needed',
    enabled: 'Enabled',
    submit: 'Confirm',
    cancel: 'Cancel',
    nameRequired: 'Name is required',
    cronRequired: 'cron expression is required',
    jsonError: 'Invalid JSON',
    createSuccess: 'Created',
    updateSuccess: 'Updated',
    getMethodsFailed: 'Failed to load registered methods'
  },
  enable: 'Enabled',
  disable: 'Disabled',
  triggerSuccess: 'Triggered, check the logs later',
  deleteConfirm: 'Delete this task?',
  deleteSuccess: 'Deleted',
  log: {
    title: 'Execution Logs',
    search: {
      triggerType: 'Trigger',
      status: 'Status',
      timeRange: 'Execution Time',
      search: 'Search',
      reset: 'Reset',
      manual: 'Manual',
      auto: 'Schedule',
      success: 'Success',
      failed: 'Failed'
    },
    columns: {
      triggerType: 'Trigger',
      status: 'Status',
      startedAt: 'Started At',
      finishedAt: 'Finished At',
      duration: 'Duration (ms)',
      createdAt: 'Created At',
      view: 'Detail'
    },
    detail: {
      title: 'Execution Detail',
      triggerType: 'Trigger',
      status: 'Status',
      startedAt: 'Started At',
      finishedAt: 'Finished At',
      duration: 'Duration (ms)',
      createdAt: 'Created At',
      error: 'Error',
      output: 'Output',
      close: 'Close'
    }
  }
};

export default timedTaskEnUS;
