const timedTaskZhCN = {
  title: '定时任务',
  search: {
    name: '任务名',
    executorType: '执行器',
    enabled: '是否启用',
    method: '注册方法',
    http: 'HTTP',
    search: '查询',
    reset: '重置'
  },
  add: '新增任务',
  columns: {
    id: 'ID',
    name: '任务名',
    description: '说明',
    spec: 'cron',
    executorType: '执行器',
    methodExecutor: '注册方法',
    httpExecutor: 'HTTP',
    enabled: '启用',
    nextRunAt: '下次执行',
    operations: '操作',
    trigger: '触发',
    logs: '日志',
    edit: '编辑',
    delete: '删除',
    cannotDeleteEnabled: '启用中的任务不可删除'
  },
  form: {
    title: '新增定时任务',
    editTitle: '编辑定时任务',
    name: '任务名',
    description: '说明',
    spec: 'cron 表达式',
    cronTemplate: '常用模板',
    withSeconds: '含秒位',
    withSecondsHint: '开启后为六位表达式(秒 分 时 日 月 周)',
    executor: '执行器',
    methodExecutor: '调用已注册方法',
    httpExecutor: 'HTTP 调用',
    method: '方法',
    params: '参数(JSON)',
    url: 'URL',
    httpMethod: 'Method',
    header: 'Header(JSON)',
    body: 'Body',
    allowPrivate: '允许内网',
    allowPrivateHint: '默认禁止访问内网/环回地址(SSRF 防护)，仅确有需要时开启',
    enabled: '启用',
    submit: '确定',
    cancel: '取消',
    nameRequired: '任务名必填',
    cronRequired: 'cron 表达式必填',
    jsonError: '不是合法 JSON',
    createSuccess: '创建成功',
    updateSuccess: '更新成功',
    getMethodsFailed: '获取已注册方法失败'
  },
  enable: '已启用',
  disable: '已停用',
  triggerSuccess: '已触发，稍后可在日志中查看结果',
  deleteConfirm: '确定删除该任务吗？',
  deleteSuccess: '删除成功',
  log: {
    title: '执行日志',
    search: {
      triggerType: '触发方式',
      status: '执行结果',
      timeRange: '执行时间',
      search: '查询',
      reset: '重置',
      manual: '手动',
      auto: '调度',
      success: '成功',
      fail: '失败',
      timeout: '超时'
    },
    columns: {
      triggerType: '触发方式',
      status: '执行结果',
      startedAt: '开始时间',
      finishedAt: '结束时间',
      duration: '耗时(ms)',
      createdAt: '记录时间',
      view: '详情'
    },
    detail: {
      title: '执行详情',
      triggerType: '触发方式',
      status: '执行结果',
      startedAt: '开始时间',
      finishedAt: '结束时间',
      duration: '耗时(ms)',
      createdAt: '记录时间',
      error: '错误信息',
      output: '输出内容',
      close: '关闭'
    }
  }
};

export default timedTaskZhCN;
