const enUS: import('../types/i18n').SystemDepartmentLang = {
  title: 'Department Management',
  addDept: 'Add Department',
  editDept: 'Edit Department',
  deleteDept: 'Delete Department',
  refresh: 'Refresh',
  colSetting: 'Column Settings',
  selectAll: 'Select All',
  search: 'Search',
  searchTitle: 'Search Department',
  reset: 'Reset',
  operation: 'Operation',
  index: 'No.',
  name: 'Name',
  parentId: 'Parent Department',
  parentIdTop: 'Top Department',
  leader: 'Leader',
  phone: 'Phone',
  email: 'Email',
  sort: 'Sort',
  status: 'Status',
  statusAll: 'All',
  enabled: 'Enabled',
  disabled: 'Disabled',
  confirmDelete: 'Are you sure to delete this department?',
  confirmBatchDelete: 'Are you sure to batch delete the selected departments?',
  expandAll: 'Expand All',
  collapseAll: 'Collapse All',
  namePlaceholder: 'Please enter the department name',
  statusPlaceholder: 'Please select status',
  parentIdPlaceholder: 'Please select the parent department',
  leaderPlaceholder: 'Click to select leader',
  leaderSearchPlaceholder: 'Search leader by nickname',
  selectLeaderBtn: 'Select',
  phonePlaceholder: 'Auto-filled after selecting leader',
  emailPlaceholder: 'Auto-filled after selecting leader',
  selectLeader: 'Select Leader',
  sortPlaceholder: 'Please enter the sort value',
  addSuccess: 'Created successfully',
  editSuccess: 'Updated successfully',
  deleteSuccess: 'Deleted successfully'
};

export default enUS;
