export default {
  title: 'User Management',
  userName: 'Username',
  nickName: 'Nickname',
  phone: 'Phone',
  email: 'Email',
  role: 'Role',
  status: 'Status',
  createdAt: 'Created At',
  operation: 'Operation',
  search: 'Search',
  searchTitle: 'Search',
  reset: 'Reset',
  addUser: 'Add User',
  editUser: 'Edit User',
  deleteUser: 'Delete User',
  batchDelete: 'Batch Delete',
  enable: 'Enable',
  disable: 'Disable',
  confirmDelete: 'Are you sure to delete this user?',
  confirmBatchDelete: 'Are you sure to batch delete selected users?',
  index: 'Index',
  selectAll: 'Select All',
  colSetting: 'Column Settings',
  refresh: 'Refresh',
  userNamePlaceholder: 'Please enter username',
  userNameMinLength: 'Username must be at least 5 characters',
  nickNamePlaceholder: 'Please enter nickname',
  phonePlaceholder: 'Please enter phone number',
  phoneInvalid: 'Invalid phone format',
  emailPlaceholder: 'Please enter email',
  emailInvalid: 'Invalid email format',
  rolePlaceholder: 'Please select role',
  statusPlaceholder: 'Please select status',
  password: 'Password',
  passwordPlaceholder: 'Please enter password',
  passwordRequired: 'Password is required',
  addSuccess: 'Created successfully',
  editSuccess: 'Updated successfully',
  deleteSuccess: 'Deleted successfully'
};
