/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  example_customer: () => import("@/views/example/customer/index.vue"),
  home: () => import("@/views/home/index.vue"),
  system_api: () => import("@/views/system/api/index.vue"),
  system_authority: () => import("@/views/system/authority/index.vue"),
  system_department: () => import("@/views/system/department/index.vue"),
  system_dictionary: () => import("@/views/system/dictionary/index.vue"),
  system_menu: () => import("@/views/system/menu/index.vue"),
  system_params: () => import("@/views/system/params/index.vue"),
  system_position: () => import("@/views/system/position/index.vue"),
  system_security: () => import("@/views/system/security/index.vue"),
  system_user: () => import("@/views/system/user/index.vue"),
  systemtools_apitoken: () => import("@/views/systemtools/apiToken/index.vue"),
  systemtools_loginlog: () => import("@/views/systemtools/loginlog/index.vue"),
  systemtools_syserror: () => import("@/views/systemtools/syserror/index.vue"),
  systemtools_system: () => import("@/views/systemtools/system/index.vue"),
  systemtools_timedtask: () => import("@/views/systemtools/timedtask/index.vue"),
  systemtools_version: () => import("@/views/systemtools/version/index.vue"),
};
