/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  example_customer: () => import("@/views/example/customer/index.vue"),
  "function_hide-child_one": () => import("@/views/function/hide-child/one/index.vue"),
  "function_hide-child_three": () => import("@/views/function/hide-child/three/index.vue"),
  "function_hide-child_two": () => import("@/views/function/hide-child/two/index.vue"),
  "function_super-page": () => import("@/views/function/super-page/index.vue"),
  home: () => import("@/views/home/index.vue"),
  "ops-monitor_login-log": () => import("@/views/ops-monitor/login-log/index.vue"),
  "ops-monitor_operation-history": () => import("@/views/ops-monitor/operation-history/index.vue"),
  "ops-monitor_server-status": () => import("@/views/ops-monitor/server-status/index.vue"),
  "ops-monitor_sys-error": () => import("@/views/ops-monitor/sys-error/index.vue"),
  "ops-monitor_timed-task": () => import("@/views/ops-monitor/timed-task/index.vue"),
  "system-tools_api-token": () => import("@/views/system-tools/api-token/index.vue"),
  "system-tools_system": () => import("@/views/system-tools/system/index.vue"),
  "system-tools_version": () => import("@/views/system-tools/version/index.vue"),
  system_api: () => import("@/views/system/api/index.vue"),
  system_authority: () => import("@/views/system/authority/index.vue"),
  system_department: () => import("@/views/system/department/index.vue"),
  system_dictionary: () => import("@/views/system/dictionary/index.vue"),
  system_menu: () => import("@/views/system/menu/index.vue"),
  system_params: () => import("@/views/system/params/index.vue"),
  system_position: () => import("@/views/system/position/index.vue"),
  system_security: () => import("@/views/system/security/index.vue"),
  system_user: () => import("@/views/system/user/index.vue"),
};
