/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'example',
    path: '/example',
    component: 'layout.base',
    meta: {
      title: 'example',
      i18nKey: 'route.example'
    },
    children: [
      {
        name: 'example_customer',
        path: '/example/customer',
        component: 'view.example_customer',
        meta: {
          title: 'example_customer',
          i18nKey: 'route.example_customer'
        }
      }
    ]
  },
  {
    name: 'function',
    path: '/function',
    component: 'layout.base',
    meta: {
      title: 'function',
      i18nKey: 'route.function'
    },
    children: [
      {
        name: 'function_hide-child',
        path: '/function/hide-child',
        meta: {
          title: 'function_hide-child',
          i18nKey: 'route.function_hide-child'
        },
        children: [
          {
            name: 'function_hide-child_one',
            path: '/function/hide-child/one',
            component: 'view.function_hide-child_one',
            meta: {
              title: 'function_hide-child_one',
              i18nKey: 'route.function_hide-child_one'
            }
          },
          {
            name: 'function_hide-child_three',
            path: '/function/hide-child/three',
            component: 'view.function_hide-child_three',
            meta: {
              title: 'function_hide-child_three',
              i18nKey: 'route.function_hide-child_three'
            }
          },
          {
            name: 'function_hide-child_two',
            path: '/function/hide-child/two',
            component: 'view.function_hide-child_two',
            meta: {
              title: 'function_hide-child_two',
              i18nKey: 'route.function_hide-child_two'
            }
          }
        ]
      },
      {
        name: 'function_super-page',
        path: '/function/super-page',
        component: 'view.function_super-page',
        meta: {
          title: 'function_super-page',
          i18nKey: 'route.function_super-page'
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'ri:dashboard-line',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'ops-monitor',
    path: '/ops-monitor',
    component: 'layout.base',
    meta: {
      title: 'ops-monitor',
      i18nKey: 'route.ops-monitor'
    },
    children: [
      {
        name: 'ops-monitor_login-log',
        path: '/ops-monitor/login-log',
        component: 'view.ops-monitor_login-log',
        meta: {
          title: 'ops-monitor_login-log',
          i18nKey: 'route.ops-monitor_login-log'
        }
      },
      {
        name: 'ops-monitor_operation-history',
        path: '/ops-monitor/operation-history',
        component: 'view.ops-monitor_operation-history',
        meta: {
          title: 'ops-monitor_operation-history',
          i18nKey: 'route.ops-monitor_operation-history'
        }
      },
      {
        name: 'ops-monitor_server-status',
        path: '/ops-monitor/server-status',
        component: 'view.ops-monitor_server-status',
        meta: {
          title: 'ops-monitor_server-status',
          i18nKey: 'route.ops-monitor_server-status'
        }
      },
      {
        name: 'ops-monitor_sys-error',
        path: '/ops-monitor/sys-error',
        component: 'view.ops-monitor_sys-error',
        meta: {
          title: 'ops-monitor_sys-error',
          i18nKey: 'route.ops-monitor_sys-error'
        }
      },
      {
        name: 'ops-monitor_timed-task',
        path: '/ops-monitor/timed-task',
        component: 'view.ops-monitor_timed-task',
        meta: {
          title: 'ops-monitor_timed-task',
          i18nKey: 'route.ops-monitor_timed-task'
        }
      }
    ]
  },
  {
    name: 'system',
    path: '/system',
    component: 'layout.base',
    meta: {
      title: 'system',
      i18nKey: 'route.system'
    },
    children: [
      {
        name: 'system_api',
        path: '/system/api',
        component: 'view.system_api',
        meta: {
          title: 'system_api',
          i18nKey: 'route.system_api'
        }
      },
      {
        name: 'system_authority',
        path: '/system/authority',
        component: 'view.system_authority',
        meta: {
          title: 'system_authority',
          i18nKey: 'route.system_authority'
        }
      },
      {
        name: 'system_department',
        path: '/system/department',
        component: 'view.system_department',
        meta: {
          title: 'system_department',
          i18nKey: 'route.system_department'
        }
      },
      {
        name: 'system_dictionary',
        path: '/system/dictionary',
        component: 'view.system_dictionary',
        meta: {
          title: 'system_dictionary',
          i18nKey: 'route.system_dictionary'
        }
      },
      {
        name: 'system_menu',
        path: '/system/menu',
        component: 'view.system_menu',
        meta: {
          title: 'system_menu',
          i18nKey: 'route.system_menu'
        }
      },
      {
        name: 'system_params',
        path: '/system/params',
        component: 'view.system_params',
        meta: {
          title: 'system_params',
          i18nKey: 'route.system_params'
        }
      },
      {
        name: 'system_position',
        path: '/system/position',
        component: 'view.system_position',
        meta: {
          title: 'system_position',
          i18nKey: 'route.system_position'
        }
      },
      {
        name: 'system_security',
        path: '/system/security',
        component: 'view.system_security',
        meta: {
          title: 'system_security',
          i18nKey: 'route.system_security'
        }
      },
      {
        name: 'system_user',
        path: '/system/user',
        component: 'view.system_user',
        meta: {
          title: 'system_user',
          i18nKey: 'route.system_user'
        }
      }
    ]
  },
  {
    name: 'system-tools',
    path: '/system-tools',
    component: 'layout.base',
    meta: {
      title: 'system-tools',
      i18nKey: 'route.system-tools'
    },
    children: [
      {
        name: 'system-tools_api-token',
        path: '/system-tools/api-token',
        component: 'view.system-tools_api-token',
        meta: {
          title: 'system-tools_api-token',
          i18nKey: 'route.system-tools_api-token'
        }
      },
      {
        name: 'system-tools_system',
        path: '/system-tools/system',
        component: 'view.system-tools_system',
        meta: {
          title: 'system-tools_system',
          i18nKey: 'route.system-tools_system'
        }
      },
      {
        name: 'system-tools_version',
        path: '/system-tools/version',
        component: 'view.system-tools_version',
        meta: {
          title: 'system-tools_version',
          i18nKey: 'route.system-tools_version'
        }
      }
    ]
  }
];
