const enUS: import('../types/i18n').SystemMenuLang = {
  title: 'Menu Management',
  addMenu: 'Add Menu',
  editMenu: 'Edit Menu',
  deleteMenu: 'Delete Menu',
  copyMenu: 'Copy Menu',
  refresh: 'Refresh',
  colSetting: 'Column Settings',
  selectAll: 'Select All',
  search: 'Search',
  searchTitle: 'Search Menu',
  reset: 'Reset',
  operation: 'Operation',
  id: 'ID',
  name: 'Route Name',
  titleField: 'Title',
  path: 'Route Path',
  component: 'Component',
  parentId: 'Parent ID',
  sort: 'Sort',
  icon: 'Icon',
  iconCountTip: 'Showing {shown} of {total} icons',
  keepAlive: 'KeepAlive',
  closeTab: 'Close Tab',
  defaultMenu: 'Default Menu',
  visibility: 'Visibility',
  show: 'Show',
  hidden: 'Hidden',
  confirmDelete: 'Are you sure to delete this menu?',
  confirmBatchDelete: 'Are you sure to batch delete the selected menus?',
  deleteDisabledHasChildren: 'Cannot delete: has child menus',
  namePlaceholder: 'Unique English string',
  titlePlaceholder: 'Please enter the menu title',
  pathPlaceholder: 'Append params after the base path only',
  componentPlaceholder: 'Please select a component path',
  componentType: 'Component Type',
  componentTypeDirectory: 'Directory (Layout)',
  componentTypeFile: 'File (Page)',
  componentTypeManual: 'Manual Input',
  componentDirPlaceholder: 'Please select a layout',
  componentFilePlaceholder: 'Please select a page component',
  parentIdPlaceholder: 'Please select the parent menu',
  sortPlaceholder: 'Please enter a sort number',
  iconPlaceholder: 'Please select',
  addSuccess: 'Created successfully',
  editSuccess: 'Updated successfully',
  deleteSuccess: 'Deleted successfully',
  /* table operations */
  addChild: 'Add Child',
  assignRole: 'Assign Role',
  /* drawer sections */
  rootDirectory: 'Root',
  selectPath: 'Select Path',
  manualInput: 'Manual Input',
  selectInput: 'Select File',
  componentInputMode: 'Input Mode',
  componentTip: 'If this menu contains child menus, please create a router-view secondary route page or',
  clickToSet: 'Click to set',
  addMenuWarning: 'New menus require permission configuration in Role Management before they can be used.',
  sectionBasic: 'Basic Info',
  sectionRoute: 'Route Config',
  sectionDisplay: 'Display Settings',
  sectionAdvanced: 'Advanced',
  sectionParams: 'Menu Parameters',
  sectionButtons: 'Menu Buttons',
  /* drawer fields */
  addParam: 'Add Param',
  sortLabel: 'Sort',
  transitionType: 'Transition Type',
  followGlobal: 'Follow Global',
  /* form validation */
  titleRequired: 'Please enter the title',
  nameRequired: 'Please enter the route name',
  componentRequired: 'Please select or enter the component path',
  parentIdRequired: 'Please select the parent node',
  pathRequired: 'Please enter the route path',
  /* parameter table */
  paramType: 'Type',
  paramKey: 'Key',
  paramValue: 'Value',
  addParamBtn: 'Add Parameter',
  paramEmptyTip: 'No parameters yet, click the button above to add',
  paramRequiredTip: 'Some required parameters are missing, please complete them before submitting',
  /* button table */
  btnName: 'Button Name',
  btnDesc: 'Description',
  addBtnBtn: 'Add Button',
  btnEmptyTip: 'No buttons yet, click the button above to add',
  btnRequiredTip: 'Some required button fields are missing, please complete them before submitting',
  /* detail panel */
  panelMenuList: 'Menu List',
  panelMenuDetail: 'Menu Detail',
  expandAll: 'Expand All',
  collapseAll: 'Collapse All',
  panelBtnPermission: 'Button Permission List',
  panelAddChild: 'Add Sub Menu',
  panelEdit: 'Edit',
  panelDelete: 'Delete',
  fieldMenuType: 'Menu Type',
  fieldMenuStatus: 'Menu Status',
  fieldMenuName: 'Menu Name',
  fieldRoutePath: 'Route Path',
  fieldIsExternal: 'Is External',
  fieldDisplayStatus: 'Display Status',
  fieldBtnPerm: 'Permission',
  fieldCreateTime: 'Create Time',
  fieldSort: 'Sort',
  typeDirectory: 'Directory',
  typeMenu: 'Menu',
  typeLink: 'External Link',
  linkAddress: 'External Link',
  linkAddressPlaceholder: 'Please enter the external link, e.g. https://example.com',
  linkPathPlaceholder: 'Auto-generated from the external link (editable)',
  linkRequired: 'Please enter the external link',
  statusNormal: 'Normal',
  statusDisabled: 'Disabled',
  externalYes: 'Yes',
  externalNo: 'No',
  btnEmpty: 'No Data',
  btnAdd: 'Add Button',
  noSelectHint: 'Please select a menu on the left to view details',
  fieldLayout: 'Layout',
  layoutBase: 'Default layout: includes common parts like global header, sidebar, footer, etc.',
  layoutBlank: 'Blank layout: no common parts, e.g. login page',
  layoutBaseLabel: 'Default',
  layoutBlankLabel: 'Blank',
  layoutPlaceholder: 'Please select a layout',
  refreshFailed: 'Failed to refresh data, please try again'
};

export default enUS;
