const enUS: import('../types/i18n').SystemMenuLang = {
  title: 'Menu Management',
  addMenu: 'Add Menu',
  editMenu: 'Edit Menu',
  deleteMenu: 'Delete Menu',
  copyMenu: 'Copy Menu',
  refresh: 'Refresh',
  colSetting: 'Column Settings',
  selectAll: 'Select All',
  search: 'Search',
  searchTitle: 'Search Menu',
  reset: 'Reset',
  operation: 'Operation',
  index: 'No.',
  name: 'Route Name',
  titleField: 'Menu Title',
  path: 'Route Path',
  component: 'Component',
  parentId: 'Parent Menu',
  sort: 'Sort',
  icon: 'Icon',
  keepAlive: 'KeepAlive',
  closeTab: 'Close Tab',
  defaultMenu: 'Default Menu',
  visibility: 'Visibility',
  show: 'Show',
  hidden: 'Hidden',
  confirmDelete: 'Are you sure to delete this menu?',
  confirmBatchDelete: 'Are you sure to batch delete the selected menus?',
  namePlaceholder: 'Please enter the route name',
  titlePlaceholder: 'Please enter the menu title',
  pathPlaceholder: 'Please enter the route path',
  componentPlaceholder: 'Please enter the component',
  parentIdPlaceholder: 'Please select the parent menu',
  sortPlaceholder: 'Please enter the sort value',
  iconPlaceholder: 'Please enter the icon',
  addSuccess: 'Created successfully',
  editSuccess: 'Updated successfully',
  deleteSuccess: 'Deleted successfully'
};

export default enUS;
