const zhCN: import('../types/i18n').SystemMenuLang = {
  title: '菜单管理',
  addMenu: '新增菜单',
  editMenu: '编辑菜单',
  deleteMenu: '删除菜单',
  copyMenu: '复制菜单',
  refresh: '刷新',
  colSetting: '列设置',
  selectAll: '全选',
  search: '搜索',
  searchTitle: '搜索菜单',
  reset: '重置',
  operation: '操作',
  index: '序号',
  name: '路由名称',
  titleField: '菜单名称',
  path: '路由路径',
  component: '文件路径',
  parentId: '父级菜单',
  sort: '排序',
  icon: '图标',
  keepAlive: '缓存',
  closeTab: '关闭标签',
  defaultMenu: '默认菜单',
  visibility: '可见性',
  show: '显示',
  hidden: '隐藏',
  confirmDelete: '确定要删除该菜单吗？',
  confirmBatchDelete: '确定要批量删除选中的菜单吗？',
  namePlaceholder: '请输入路由名称',
  titlePlaceholder: '请输入菜单名称',
  pathPlaceholder: '请输入路由路径',
  componentPlaceholder: '请输入文件路径',
  parentIdPlaceholder: '请选择父级菜单',
  sortPlaceholder: '请输入排序值',
  iconPlaceholder: '请输入图标',
  addSuccess: '新增成功',
  editSuccess: '编辑成功',
  deleteSuccess: '删除成功'
};

export default zhCN;
