const zhCN: import('../types/i18n').SystemMenuLang = {
  title: '菜单管理',
  addMenu: '新增菜单',
  editMenu: '编辑菜单',
  deleteMenu: '删除菜单',
  copyMenu: '复制菜单',
  refresh: '刷新',
  colSetting: '列设置',
  selectAll: '全选',
  search: '搜索',
  searchTitle: '搜索菜单',
  reset: '重置',
  operation: '操作',
  id: 'ID',
  name: '路由名称',
  titleField: '展示名称',
  path: '路由路径',
  component: '文件路径',
  parentId: '上级菜单',
  sort: '排序',
  icon: '图标',
  iconCountTip: '显示 {shown} 个，共 {total} 个图标',
  keepAlive: '缓存',
  closeTab: '关闭标签',
  defaultMenu: '是否为基础页面',
  visibility: '是否隐藏',
  show: '显示',
  hidden: '隐藏',
  confirmDelete: '确定要删除该菜单吗？',
  confirmBatchDelete: '确定要批量删除选中的菜单吗？',
  deleteDisabledHasChildren: '存在子菜单，不允许删除',
  namePlaceholder: '唯一英文字符串',
  titlePlaceholder: '请输入菜单展示名称',
  pathPlaceholder: '建议只在后方拼接参数',
  componentPlaceholder: '请选择文件路径',
  componentType: '组件类型',
  componentTypeDirectory: '目录（父级容器）',
  componentTypeFile: '最终文件（页面）',
  componentTypeManual: '手动输入',
  componentDirPlaceholder: '请选择布局容器',
  componentFilePlaceholder: '请选择页面组件',
  parentIdPlaceholder: '请选择父级菜单',
  sortPlaceholder: '请输入排序数字',
  iconPlaceholder: '请选择',
  addSuccess: '新增成功',
  editSuccess: '编辑成功',
  deleteSuccess: '删除成功',
  /* table operations */
  addChild: '添加子菜单',
  assignRole: '分配角色',
  /* drawer sections */
  rootDirectory: '根目录',
  selectPath: '选择路径',
  manualInput: '手动输入',
  selectInput: '选择文件',
  componentInputMode: '录入方式',
  componentTip: '如果菜单包含子菜单，请创建router-view二级路由由页面或者',
  clickToSet: '点我设置',
  addMenuWarning: '新增菜单，需要在角色管理内配置权限才可使用',
  sectionBasic: '基础信息',
  sectionRoute: '路由配置',
  sectionDisplay: '显示设置',
  sectionAdvanced: '高级配置',
  sectionParams: '菜单参数配置',
  sectionButtons: '可控按钮配置',
  /* drawer fields */
  addParam: '添加参数',
  sortLabel: '排序',
  transitionType: '路由切换动画',
  followGlobal: '跟随全局',
  /* form validation */
  titleRequired: '请输入展示名称',
  nameRequired: '请输入路由名称',
  componentRequired: '请选择或输入文件路径',
  parentIdRequired: '请选择父节点',
  pathRequired: '请输入路由路径',
  /* parameter table */
  paramType: '参数类型',
  paramKey: '参数key',
  paramValue: '参数值',
  addParamBtn: '新增菜单参数',
  paramEmptyTip: '暂无菜单参数，点击上方按钮新增',
  paramRequiredTip: '菜单参数存在未填写的必填项，请补全后再提交',
  /* button table */
  btnName: '按钮名称',
  btnDesc: '备注',
  addBtnBtn: '新增可控按钮',
  btnEmptyTip: '暂无可控按钮，点击上方按钮新增',
  btnRequiredTip: '可控按钮存在未填写的必填项，请补全后再提交',
  /* detail panel */
  panelMenuList: '菜单列表',
  panelMenuDetail: '菜单详情',
  expandAll: '展开全部',
  collapseAll: '折叠全部',
  panelBtnPermission: '按钮权限列表',
  panelAddChild: '新增子菜单',
  panelEdit: '编辑',
  panelDelete: '删除',
  fieldMenuType: '菜单类型',
  fieldMenuStatus: '菜单状态',
  fieldMenuName: '菜单名称',
  fieldRoutePath: '路由地址',
  fieldIsExternal: '是否外链',
  fieldDisplayStatus: '显示状态',
  fieldBtnPerm: '权限字符',
  fieldCreateTime: '创建时间',
  fieldSort: '排序',
  typeDirectory: '目录',
  typeMenu: '菜单',
  typeLink: '外链',
  linkAddress: '外链地址',
  linkAddressPlaceholder: '请输入外部链接地址，如 https://example.com',
  linkPathPlaceholder: '由外链地址自动生成（可手动修改）',
  openInProject: '是否项目内打开',
  openInProjectTip: '是：在项目内嵌入页面打开；否：在浏览器新标签页打开',
  linkRequired: '请输入外链地址',
  linkFormatInvalid: '外链地址格式不正确，需以 http:// 或 https:// 开头',
  statusNormal: '正常',
  statusDisabled: '停用',
  externalYes: '是',
  externalNo: '否',
  btnEmpty: '暂无数据',
  btnAdd: '新增按钮',
  noSelectHint: '请在左侧选择一个菜单查看详情',
  fieldLayout: '布局方式',
  layoutBase: '默认布局：具有公共部分的布局，如全局头部、侧边栏、底部等',
  layoutBlank: '空白布局：无公共部分的布局，如登录页',
  layoutBaseLabel: '默认布局',
  layoutBlankLabel: '空白布局',
  layoutPlaceholder: '请选择布局方式',
  refreshFailed: '刷新数据失败，请重试'
};

export default zhCN;
