const enUS: import('../types/i18n').SystemPositionLang = {
  title: 'Position Management',
  positionList: 'Position List',
  searchPosition: 'Search Position',
  members: 'Members',
  saveMembers: 'Save Members',
  userName: 'Username',
  nickName: 'Nickname',
  query: 'Query',
  addPosition: 'Add Position',
  editPosition: 'Edit Position',
  deletePosition: 'Delete Position',
  refresh: 'Refresh',
  colSetting: 'Column Settings',
  selectAll: 'Select All',
  search: 'Search',
  searchTitle: 'Search Position',
  reset: 'Reset',
  operation: 'Operation',
  index: 'No.',
  name: 'Name',
  code: 'Code',
  sort: 'Sort',
  status: 'Status',
  remark: 'Remark',
  enabled: 'Enabled',
  disabled: 'Disabled',
  confirmDelete: 'Are you sure to delete this position?',
  confirmBatchDelete: 'Are you sure to batch delete the selected positions?',
  namePlaceholder: 'Please enter the position name',
  codePlaceholder: 'Please enter the position code',
  sortPlaceholder: 'Please enter the sort value',
  remarkPlaceholder: 'Please enter a remark',
  userNamePlaceholder: 'Please enter the username',
  nickNamePlaceholder: 'Please enter the nickname',
  addSuccess: 'Created successfully',
  editSuccess: 'Updated successfully',
  deleteSuccess: 'Deleted successfully',
  saveSuccess: 'Saved successfully',
  selectPositionFirst: 'Please select a position first',
  totalItems: 'Total {total} items',
  perPage: 'per page'
};

export default enUS;