export default {
  title: 'Role Management',
  authorityId: 'Role ID',
  authorityName: 'Role Name',
  parentRole: 'Parent Role',
  dataScope: 'Data Scope',
  allData: 'All Data',
  deptAndBelow: 'Dept & Below',
  deptOnly: 'Current Dept',
  selfOnly: 'Only Self',
  customDept: 'Custom Dept',
  operation: 'Operation',
  search: 'Search',
  reset: 'Reset',
  addRole: 'Add Role',
  editRole: 'Edit Role',
  copyRole: 'Copy Role',
  addChildRole: 'Add Sub Role',
  deleteRole: 'Delete Role',
  confirmDelete: 'Are you sure to delete this role?',
  confirmCopy: 'Are you sure to copy this role?',
  selectAll: 'Select All',
  colSetting: 'Column Settings',
  refresh: 'Refresh',
  addSuccess: 'Created successfully',
  editSuccess: 'Updated successfully',
  copySuccess: 'Copied successfully',
  deleteSuccess: 'Deleted successfully',
  authorityIdPlaceholder: 'Please enter role ID',
  authorityNamePlaceholder: 'Please enter role name'
};
