export default {
  title: 'Role Management',
  authorityId: 'Role ID',
  authorityName: 'Role Name',
  parentRole: 'Parent Role',
  rootRole: 'Root Role',
  dataScope: 'Data Scope',
  allData: 'All Data',
  deptAndBelow: 'Dept & Below',
  deptOnly: 'Current Dept',
  selfOnly: 'Only Self',
  customDept: 'Custom Dept',
  operation: 'Operation',
  search: 'Search',
  reset: 'Reset',
  addRole: 'Add Role',
  editRole: 'Edit Role',
  addChildRole: 'Add Sub Role',
  deleteRole: 'Delete Role',
  setPermission: 'Set Permission',
  assignUser: 'Assign Users',
  permissionTitle: 'Role Configuration',
  assignUserTitle: 'Assign Users',
  assignUserNotice:
    'Saving will overwrite all user associations for this role. If a user has only this role, the primary role will remain unchanged after removal.',
  permissionSuccess: 'Permission set successfully',
  roleMenu: 'Role Menu',
  roleApi: 'Role API',
  filterMenu: 'Filter',
  filterApiName: 'Filter name',
  filterApiPath: 'Filter path',
  defaultHomepage: 'Default homepage',
  groupSuffix: ' Group',
  otherGroup: 'Other',
  assignBtn: 'Assign Button',
  assignBtnTitle: 'Assign Button',
  assignBtnSuccess: 'Buttons assigned successfully',
  btnName: 'Button Name',
  btnDesc: 'Button Remark',
  assignSuccess: 'Users assigned successfully',
  userSearchPlaceholder: 'Search username / nickname',
  confirmDelete: 'Are you sure to delete this role?',
  selectAll: 'Select All',
  colSetting: 'Column Settings',
  refresh: 'Refresh',
  addSuccess: 'Created successfully',
  editSuccess: 'Updated successfully',
  deleteSuccess: 'Deleted successfully',
  authorityIdPlaceholder: 'Please enter role ID',
  authorityIdPositiveInt: 'Role ID must be a positive integer',
  authorityNamePlaceholder: 'Please enter role name',
  parentRolePlaceholder: 'Please select a parent role'
};
